### ISSUE TITLE
Bug. Train leaves the station when station is disabled but conditions are not met

### ISSUE THREAD

**Issue by Dmitrykrz** [shanemadden/factorio-accumulator-wagon#3]
Normally when a train station is disabled the train wait for its conditions to meet and leave the station aftewards. I have found a situation when train leaves the station before unloading is finished (accumulator wagon).
Have a look at the screenshot. The train is set to leave when accumulator fluid is zero. But instead it leaves after half a second of powering this one factory,

![image](https://user-images.githubusercontent.com/25010053/50677835-108ff580-100d-11e9-8a4a-bdec4664a263.png)

I have tested this on a clean save with no other mods.

Here is the test blueprint

`0eNqdmdFumzAUhl9l8jVU2GADkXa1PcLupipywG0sgUHGqVZVefdhSJO0M/M5vUkChs+/zfntw8kbOXQnNVptHNm9Ed0MZiK7329k0s9Gdv6cex0V2RHtVE8SYmTvj6zUHTknRJtW/SE7ek6it0xDJ206SqPu72Tnx4Qo47TTau15OXjdm1N/UHZGBwEJGYdpvmcwvr+Zk/IHnpDX+QfNHvjZ6/kEYldQr1p96lPVqcZZ3aTj0KkAMb8SWZiYA6WxmLQCBspiHI4cIouNUMCE5TFhJYwjYpwKOcAyNsAaJqyOCaPZFdSc7Itq08UhgVioV1A9W6DVdla/NIoQk0KZNMjMQ0wGY24ggzJzILKGq7wzhJtpz0e3NfacrVTxkVqGqBxMpVWQSkNUgV2gyo0QKrHLyRaoQi4nW5wa6f4NDsuQ7t/iUKRZtzgMGgcbYRAKLpZDoRsRG4otVgBXgPwy4hzARLhABJXyEFUAlfrVIqA0OKUljLmBZCFkBX704bGHVitWw3TeHlIol7iZxAsz6eSGMTB/l4gsPq3LyTweuf4mP47SPmvz/O39VKg7+uVsqNhIhthXk48tYP7VzX4LCN9VLrPM4hGVw+0k4FABhhZwaAmGMjgUbKgMzqyhTLjOIoMy4RNaUCgT/uQL8N4ED9Eix+0i/COyCCEL1JLH4xtIwXEbCI8npoVA+r0AzGWJtDuEWSHdDmHWSLMDmDzDeR2CpDirQ5AM53QIMscZHYIscD6HIDkqXeLxxIYLbKpYxbM6XmIzD3rZ18VG0aMCZU7rPH5K5+ZYaQbj7NDtD+ooX/Rg/eWNts1Ju/3c1l4ZT9pObv9PketFW3eS3V2da7ki/eWLXL6c5qSvrWX+oB+llc73Qb4vzZd+lJGHTu1bPflvsnP2pOaMTpl274b9Miqye5LdNJ+1SrZ7P8RRte9N6/XLwbUJI3RVatZZmfw91H9Y1d5X5PR8JPj50V9+yzZ/6qnxCacKpZm8RubbVfwFRmTY4kAV334ExdVvKI1HumC4+s1nZsjkIsfWMKq4z8VtMZLTpPpDN789pL1sjtqoNP9PCWJ+1T77kGz0EmKj/wp1cJck97LrYpan76WJcuEDY5NXPjZD3QvkCz8kYEpUIQ0ULxWqkAYKlxpZlQBES3nvP6W6tDmqyf2n4FVv1IRvlnuSk0u1mZR1c0sg7fkQbpG0r2QwfVlEXg6Wl23Le0zWf0F2d/+zJORF2Wm9oCoZq2idlex8/guQUmLb`

**Comment by Dmitrykrz** [comment]
The accumulator wagon seems to affect the train behavior in a strange way.
If I set the train to wait 5 seconds at charge station and wait 5 seconds at discharge station it works fine even when discharge station is auto-disabled.
If I add accumulator wagon to the train, charged or not charged, the train now leaves the station WITHOUT waiting 5 seconds. Even if the power wires are not connected to the wagon, even if train condition do not mention accumulator fluid at all.

**Comment by shanemadden** [comment]
I see why this is happening and it should be a relatively easy fix, thanks!

**Comment by Dmitrykrz** [comment]
Problem solved. Thanks. I like this mod.
