### ISSUE TITLE
Prioritize charging/discharging signal suggestion

### ISSUE THREAD

**Issue by Dmitrykrz** [shanemadden/factorio-accumulator-wagon#4]
This signal only change the behavior of a train when it parks. If the signal changes during train stop the behavior do not change.
Could you please make it so the train always listens to that signals?
Imagine I have 2 discharge stops on one electrical network. I want to discharge trains not equally but sequentially, so the first train to get empty leaves first. I want to compare the battery train contents and adjust discharge priorities.

**Comment by shanemadden** [comment]
That's a really interesting way to use this mod, I hadn't thought of that! There will be a bit of performance cost of checking the signals while parked so if it costs too much I'll put an option around it, but definitely doable.

**Comment by Dmitrykrz** [comment]
Maybe check the signals once a second not each tick? There is definitely no need to change the priorities faster than once a second.
One more suggestions. Could you please put more info about those signals into the mod description. I have found those things while digging deep into your mod. Most guys will not dig that deep and will not discover such a cool feature without a description on a mod portal.

**Comment by shanemadden** [comment]
Yup - the mod is already doing work every 30 ticks for every parked accumulator wagon, to sync the level of fluid in the wagon and the level of energy in the invisible accumulator. This'll just be a few additional steps on top of that (2x hits to the C API so they're not inconsequential but, they won't hurt much); querying the station from the train, grabbing the signals from the station entity, and checking the signals for the ones the mod cares about.

As far as the documentation, definitely - there's a short description of how the signals work in the information tab on the mod portal, but I've been meaning to improve that readme - and the description should be improved as well. I'll see about updating them.

**Comment by shanemadden** [comment]
The performance cost ended up being very minor, so I went ahead and just enabled the 'check signals every half second' behavior by default in the new version. Let me know if you have any issues!

**Comment by Dmitrykrz** [comment]
Thanks, now it works exactly as I wanted.
