### ISSUE TITLE
Bug. Accumulator fluid is stuck at 0.0

### ISSUE THREAD

**Issue by Dmitrykrz** [shanemadden/factorio-accumulator-wagon#5]
Sometimes the accumulator fluid is stuck at 0.0 but not zero. Almost as if the fluid amount is something like 0.01. This causes train not to leave (is it set to leave when cargo inventory is empty). Since 0.0 is not empty is does not leave. This happens very rarely, maybe one per 50 train parkings.
Here is the screenshot

![image](https://user-images.githubusercontent.com/25010053/50742050-37217c80-1217-11e9-9e10-b07be9646301.png)

**Comment by shanemadden** [comment]
Oh, huh - I'd run into this at not-quite-full but hadn't seen it at not-quite empty. I think I know what's needed to fix.

**Comment by shanemadden** [comment]
This should hopefully be fixed in the new version, let me know if you're still seeing it

**Comment by Dmitrykrz** [comment]
Done
